"""FusionScoringStub Analysis_Stage_Stub Lambda (Task 11.4).

Draws clipCount in [3, 10] from the seeded PRNG (see lambdas/common/prng.py
-- seeded only from jobId + sourceKeys[] + targets[], so re-runs with an
unchanged Job identity reproduce identical output, Req 6.6, 6.8). For each
clip generates non-overlapping start/end windows over a fixed placeholder
timeline, score in [0, 100], factors{chat, audio, visual, speech} each in
[-100, 100], titleNative/titleEnglish/caption/hashtags[]/videoKey/thumbKey
-- all derived from the same rng instance in a fixed draw order so output
is deterministic per Job identity (Req 6.3, 6.7).

Publishes started/completed progress events like the no-op stages
(Req 5.2) and writes the generated Clip records directly to the Clip table
so CategorizationStub (which runs next) can load and update them.

Validates: Requirements 6.3, 6.7 (Property 13, 14)
"""
from lambdas.common.ddb import clip_table
from lambdas.common.prng import seeded_rng
from lambdas.progress_api.push import publish_progress_event

STAGE_NAME = "fusion/scoring"

TIMELINE_SECONDS = 3600.0  # fixed placeholder timeline duration
MIN_CLIP_LEN = 15.0
MAX_CLIP_LEN = 75.0

FACTOR_NAMES = ("chat", "audio", "visual", "speech")

HASHTAG_POOL = [
    "#highlight", "#moment", "#clip", "#viral", "#funny", "#hype",
    "#emotional", "#wholesome", "#reaction", "#livestream", "#gaming",
    "#talkshow", "#mustwatch", "#trending", "#fyp",
]

TITLE_TEMPLATES_NATIVE = [
    "精彩片段 #{n}",
    "太好笑了 #{n}",
    "全場歡呼的瞬間 #{n}",
    "令人感動的一刻 #{n}",
]

TITLE_TEMPLATES_ENGLISH = [
    "Highlight Moment #{n}",
    "The Crowd Went Wild #{n}",
    "An Unforgettable Moment #{n}",
    "This Had Everyone Laughing #{n}",
]

CAPTION_TEMPLATE = (
    "Placeholder caption for clip #{n} generated by Analysis_Stage_Stub. "
    "Real virality scoring and captioning are out of scope for the "
    "webapp-skeleton spec."
)


def _non_overlapping_windows(rng, count: int):
    """Partition TIMELINE_SECONDS into `count` non-overlapping windows in
    chronological order, each within [MIN_CLIP_LEN, MAX_CLIP_LEN]."""
    windows = []
    cursor = 0.0
    remaining_slots = count
    for i in range(count):
        remaining_len = TIMELINE_SECONDS - cursor
        remaining_min_needed = MIN_CLIP_LEN * (remaining_slots - 1)
        max_len_here = min(MAX_CLIP_LEN, remaining_len - remaining_min_needed)
        max_len_here = max(MIN_CLIP_LEN, max_len_here)
        length = round(rng.uniform(MIN_CLIP_LEN, max_len_here), 2)
        gap = round(rng.uniform(0, 20), 2) if i > 0 else round(rng.uniform(0, 60), 2)
        start = round(cursor + gap, 2)
        end = round(start + length, 2)
        windows.append((start, end))
        cursor = end
        remaining_slots -= 1
    return windows


def _make_clip(rng, clip_index: int, start: float, end: float) -> dict:
    clip_id = f"c-{clip_index + 1}"
    score = round(rng.uniform(0, 100), 2)
    factors = {name: round(rng.uniform(-100, 100), 2) for name in FACTOR_NAMES}

    n = clip_index + 1
    title_native = rng.choice(TITLE_TEMPLATES_NATIVE).format(n=n)[:100]
    title_english = rng.choice(TITLE_TEMPLATES_ENGLISH).format(n=n)[:100]
    caption = CAPTION_TEMPLATE.format(n=n)[:500]

    hashtag_count = rng.randint(1, 10)
    hashtags = rng.sample(HASHTAG_POOL, k=min(hashtag_count, len(HASHTAG_POOL)))
    while len(hashtags) < hashtag_count:
        hashtags.append(f"#clip{n}{len(hashtags)}"[:30])
    hashtags = [h[:30] for h in hashtags]

    return {
        "clipId": clip_id,
        "start": start,
        "end": end,
        "score": score,
        "factors": factors,
        "titleNative": title_native,
        "titleEnglish": title_english,
        "caption": caption,
        "hashtags": hashtags,
        "thumbKey": f"stub/{clip_id}/thumb.jpg",
        "videoKey": f"stub/{clip_id}/video.mp4",
        "cropConfirmed": False,
    }


def handler(event, context):  # noqa: ARG001
    job_id = event["jobId"]
    source_keys = event.get("sourceKeys", [])
    targets = event.get("targets", [])

    publish_progress_event(job_id, STAGE_NAME, "started")

    rng = seeded_rng(job_id, source_keys, targets, purpose="fusion")
    clip_count = rng.randint(3, 10)
    windows = _non_overlapping_windows(rng, clip_count)

    clips = [
        _make_clip(rng, i, start, end) for i, (start, end) in enumerate(windows)
    ]

    table = clip_table()
    for clip in clips:
        table.put_item(Item={"jobId": job_id, **clip})

    publish_progress_event(job_id, STAGE_NAME, "completed")

    return {**event, "clipIds": [c["clipId"] for c in clips]}
